// Generated from Figma design contract + country_flag_mapping.py. Do not edit by hand.
// Regenerate with: python3 src/figma/generate_country_flags_swift.py

import Foundation

/// Country → emoji (derived from Figma • Flags ISO codes; fallback 🌍 for unknown).
let countryFlags: [String: String] = [
    "Albania": "🇦🇱",
    "Antarctica": "🇦🇶",
    "Argentina": "🇦🇷",
    "Armenia": "🇦🇲",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Belgium": "🇧🇪",
    "Bolivia": "🇧🇴",
    "Brazil": "🇧🇷",
    "Bulgaria": "🇧🇬",
    "Canada": "🇨🇦",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Colombia": "🇨🇴",
    "Croatia": "🇭🇷",
    "Cyprus": "🇨🇾",
    "Czech Republic": "🇨🇿",
    "Denmark": "🇩🇰",
    "Finland": "🇫🇮",
    "France": "🇫🇷",
    "Georgia": "🇬🇪",
    "Germany": "🇩🇪",
    "Great Britain": "🇬🇧",
    "Greece": "🇬🇷",
    "Hong Kong": "🇭🇰",
    "Hungary": "🇭🇺",
    "Ireland": "🇮🇪",
    "Israel": "🇮🇱",
    "Italy": "🇮🇹",
    "Japan": "🇯🇵",
    "Lebanon": "🇱🇧",
    "Luxembourg": "🇱🇺",
    "Mexico": "🇲🇽",
    "Moldova": "🇲🇩",
    "Monaco": "🇲🇨",
    "Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Norway": "🇳🇴",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Romania": "🇷🇴",
    "Russia": "🇷🇺",
    "Serbia": "🇷🇸",
    "Singapore": "🇸🇬",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "South Africa": "🇿🇦",
    "Spain": "🇪🇸",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Turkey": "🇹🇷",
    "UK": "🇬🇧",
    "Ukraine": "🇺🇦",
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
    "Uruguay": "🇺🇾",
    "USA": "🇺🇸",
    "Westeros": "\u{1F30D}"
]

/// Asset name for country flag image (e.g. "flag-us"). Sourced from Figma • Flags.
let countryFlagAssets: [String: String] = [
    "Albania": "flag-al",
    "Antarctica": "flag-aq",
    "Argentina": "flag-ar",
    "Armenia": "flag-am",
    "Australia": "flag-au",
    "Austria": "flag-at",
    "Belgium": "flag-be",
    "Bolivia": "flag-bo",
    "Brazil": "flag-br",
    "Bulgaria": "flag-bg",
    "Canada": "flag-ca",
    "Chile": "flag-cl",
    "China": "flag-cn",
    "Colombia": "flag-co",
    "Croatia": "flag-hr",
    "Cyprus": "flag-cy",
    "Czech Republic": "flag-cz",
    "Denmark": "flag-dk",
    "Finland": "flag-fi",
    "France": "flag-fr",
    "Georgia": "flag-ge",
    "Germany": "flag-de",
    "Great Britain": "flag-gb",
    "Greece": "flag-gr",
    "Hong Kong": "flag-hk",
    "Hungary": "flag-hu",
    "Ireland": "flag-ie",
    "Israel": "flag-il",
    "Italy": "flag-it",
    "Japan": "flag-jp",
    "Lebanon": "flag-lb",
    "Luxembourg": "flag-lu",
    "Mexico": "flag-mx",
    "Moldova": "flag-md",
    "Monaco": "flag-mc",
    "Netherlands": "flag-nl",
    "New Zealand": "flag-nz",
    "Norway": "flag-no",
    "Poland": "flag-pl",
    "Portugal": "flag-pt",
    "Romania": "flag-ro",
    "Russia": "flag-ru",
    "Serbia": "flag-rs",
    "Singapore": "flag-sg",
    "Slovakia": "flag-sk",
    "Slovenia": "flag-si",
    "South Africa": "flag-za",
    "Spain": "flag-es",
    "Sweden": "flag-se",
    "Switzerland": "flag-ch",
    "Turkey": "flag-tr",
    "UK": "flag-gb",
    "Ukraine": "flag-ua",
    "United Kingdom": "flag-gb",
    "United States": "flag-us",
    "Uruguay": "flag-uy",
    "USA": "flag-us",
    "Westeros": "flag-xx"
]
